theme: jekyll-theme-minimal

repository: moleson21/moleson21.github.io
logo: assets/logo.jpg
description: Welcome to my website!
title: Mitchell Oleson
author: Mitchell Oleson

paginate: 25
paginate_path: "/blog/page:num/"

plugins:
  - jekyll-paginate
